config/routes.rb
Todo::Application.routes.draw do
  devise_for :users
  resources :tasks
  resources :tags
  resources :tasklists
  get "home/index"
  root to: "home#index"
end

app/models/tasklist.rb
class Tasklist < ActiveRecord::Base
  attr_accessible :name
  has_many :tasks, dependent: :destroy
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  # GET /tasklists
  # GET /tasklists.json
  def index
    @tasklists = Tasklist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasklists }
    end
  end

  # GET /tasklists/1
  # GET /tasklists/1.json
  def show
    @tasklist = Tasklist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tasklist }
    end
  end

  # GET /tasklists/new
  # GET /tasklists/new.json
  def new
    @tasklist = Tasklist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tasklist }
    end
  end

  # GET /tasklists/1/edit
  def edit
    @tasklist = Tasklist.find(params[:id])
  end

  # POST /tasklists
  # POST /tasklists.json
  def create
    @tasklist = Tasklist.new(params[:tasklist])

    respond_to do |format|
      if @tasklist.save
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully created.' }
        format.json { render json: @tasklist, status: :created, location: @tasklist }
      else
        format.html { render action: "new" }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasklists/1
  # PUT /tasklists/1.json
  def update
    @tasklist = Tasklist.find(params[:id])

    respond_to do |format|
      if @tasklist.update_attributes(params[:tasklist])
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasklists/1
  # DELETE /tasklists/1.json
  def destroy
    @tasklist = Tasklist.find(params[:id])
    @tasklist.destroy

    respond_to do |format|
      format.html { redirect_to tasklists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/views/tasklists/_form.html.haml
= form_for(@tasklist) do |f|
  - if @tasklist.errors.any?
    #error_explanation
      %h2
        = pluralize(@tasklist.errors.count, "error")
        prohibited this tasklist from being saved:
      %ul
        - @tasklist.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/tasklists/edit.html.haml
%h1 Editing tasklist
= render 'form'
= link_to 'Show', @tasklist
|
\#{link_to 'Back', tasklists_path}

app/views/tasklists/index.html.haml
%h1 Listing tasklists
%table
  %tr
    %th Name
    %th
    %th
    %th
  - @tasklists.each do |tasklist|
    %tr
      %td= tasklist.name
      %td= link_to 'Show', tasklist
      %td= link_to 'Edit', edit_tasklist_path(tasklist)
      %td= link_to 'Destroy', tasklist, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Tasklist', new_tasklist_path

app/views/tasklists/new.html.haml
%h1 New tasklist
= render 'form'
= link_to 'Back', tasklists_path

app/views/tasklists/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @tasklist.name
= link_to 'Edit', edit_tasklist_path(@tasklist)
|
\#{link_to 'Back', tasklists_path}